### ISSUE TITLE
how does DNI updating works really? a quick question

### ISSUE THREAD

**Issue by martianmartian** [andrewliao11/dni.pytorch#3]
Say there's a 4 layer network, using DNI, does the first layer get updated 4 times during each forward-backward cycle? i couldn't find out from the paper..

**Comment by andrewliao11** [comment]
just once. there's no reason to update the first layer multiple times for each batch

**Comment by andrewliao11** [comment]
I'll first close this issue.
feel free to reopen it if there are other questions
